spin_manifest_version = 2

[application]
name = "finicky-whiskers"
version = "1.1.0"

[application.trigger.http]
base = "/"

[[trigger.http]]
id = "trigger-fileserver"
component = "fileserver"
route = "/..."

[[trigger.http]]
id = "trigger-redirect-to-index"
component = "redirect-to-index"
route = "/"
executor = { type = "wagi" }

[[trigger.http]]
id = "trigger-tally"
component = "tally"
route = "/tally"

[[trigger.http]]
id = "trigger-session"
component = "session"
route = "/session"

[[trigger.http]]
id = "trigger-scoreboard"
component = "scoreboard"
route = "/score"

[[trigger.http]]
id = "trigger-highscore"
component = "highscore"
route = "/highscore"

[[trigger.http]]
id = "trigger-reset"
component = "reset"
route = "/reset"

[component.fileserver]
source = "components/fileserver.wasm"
files = [{ source = "site/dist", destination = "/" }]

[component.fileserver.build]
command = "make"
workdir = "site"

[component.redirect-to-index]
source = "components/redirect.wasm"
environment = { DESTINATION = "/index.html" }

[component.redirect-to-index.build]
command = "make"
workdir = "redirect"
watch = ["**/*.go", "go.mod"]

[component.tally]
source = "components/tally.wasm"
allowed_outbound_hosts = ["redis://*:*"]
key_value_stores = ["default"]

[component.tally.build]
command = "make"
workdir = "tally"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.session]
source = "components/sessionv2.wasm"

[component.session.build]
command = "make build"
workdir = "sessionv2"
watch = ["src/**/*.ts", "package.json"]

[component.scoreboard]
source = "components/scoreboard.wasm"
allowed_outbound_hosts = ["redis://*:*"]
key_value_stores = ["default"]

[component.scoreboard.build]
command = "make"
workdir = "scoreboard"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.highscore]
source = "components/highscore.wasm"
sqlite_databases = ["default"]

[component.highscore.build]
command = "make"
workdir = "highscore"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.reset]
source = "components/reset.wasm"
allowed_outbound_hosts = ["redis://*:*"]
key_value_stores = ["default"]
sqlite_databases = ["default"]

[component.reset.build]
command = "make"
workdir = "reset"
watch = ["src/**/*.rs", "Cargo.toml"]
